#!/usr/bin/env bash
usage="$(basename "$0")
NAME
      hashicorp - downloads hashicorp binary given a product, version,
      and directory to download to.

SYNOPSIS
      hashicorp [-h] [-d directory] -v version -p product

ARGUMENTS
       -p
       -v version
          Version of the Vault binary that you want to download. This
          value should match whatever version is specified in the 'run'
          bash script in this project (VAULT_VERSION at top of script)

          Example:
              ./download_vault -v 0.9.0

       [-d directory]
           Directory to download binary to. Defaults to HOME/.local/bin.
           Provide this flag with a file path that is in your PATH if
           the default path is not.

"

function pe() {
    echo -e "Error: $1" >&2
    exit 1
}

directory=$HOME/.local/bin

while test $# -gt 0; do
	  case "$1" in
        -h|--help|-\?)
            echo "$usage" >&2
            exit
            ;;
        -v|--version)
            version=$2
            shift
            ;;
        -d|--directory)
            directory=$2
            shift
            ;;
        -p|--product)
            product=$2
            shift
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        *)
            pe "Invalid flag: $1"
            ;;
    esac
    shift
done

if [ -z ${version} ]; then
    echo "version must be set using -v or --version"
    exit 1
fi

if [[ $product -ne "packer" || $product -ne "vault" || $product -ne "nomad" || $product -ne "consul" ]]; then
    pe "--product must be one of [\"packer\", \"vault\"]"
fi


echo "downloading ${product} binary version ${version}"
link="https://releases.hashicorp.com/${product}/${version}/${product}_${version}_linux_amd64.zip"

status_code=$(curl -s -o /dev/null -w "%{http_code}" "${link}")
if [ $status_code == 403 ]; then
    echo "${product} version ${version} does not exist"
    exit 1
fi

curl -sS "${link}" > "${product}_${version}.zip"
unzip -oq "${product}_${version}.zip"
rm $directory/$product &>/dev/null
mv $product $directory
rm "${product}_${version}.zip"

$product --version
